const h2 = document.createElement("h2");
h2.textContent = "Generated by Javascript";

document.querySelector("body").appendChild(h2);

// First Text box
document.getElementById("intro").addEventListener("mouseover", mouseOver);
document.getElementById("intro").addEventListener("mouseout", mouseOut);
      
function mouseOver() {
  document.getElementById("intro").style.borderColor = "#FDB9FF";
}
      
function mouseOut() {
  document.getElementById("intro").style.borderColor = "#B9FFFD";
}

//Image Box
document.getElementById("Image_Block").addEventListener("mouseover", mouseOver1);
document.getElementById("Image_Block").addEventListener("mouseout", mouseOut1);
      
function mouseOver1() {
  document.getElementById("Image_Block").style.borderColor = "#FDB9FF";
}
      
function mouseOut1() {
  document.getElementById("Image_Block").style.borderColor = "#B9FFFD";
}

